//! Stickers the user places over the app from the Decorations page — purely
//! cosmetic, persisted inside `settings.json` (see `Settings::decorations`).
//!
//! Everything read from disk or sent by the frontend goes through
//! [`Decorations::sanitized`]: the art is a closed list ([`StickerKind`]),
//! positions are percentages of the window, and the count is capped, so a
//! hand-edited or stale file can neither break loading nor paint something
//! huge across the window.

use serde::{Deserialize, Serialize};

/// Most stickers kept at once. Generous for decorating, small enough that the
/// overlay stays cheap to render.
pub const MAX_STICKERS: usize = 40;

/// Size is a percentage of the window's width, so a sticker keeps its place
/// and proportion in the Decorations preview and at any window size.
pub const MIN_SIZE: f32 = 2.0;
pub const MAX_SIZE: f32 = 25.0;
pub const DEFAULT_SIZE: f32 = 7.0;

/// The sticker art shipped with the app, `src/assets/stickers/<kind>.svg`.
/// Grouped by the palette's categories; the grouping itself lives in the
/// frontend (`stores/decorations.ts`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum StickerKind {
    // Girls
    Bow,
    Heart,
    Sparkle,
    Star,
    Sakura,
    Cloud,
    Strawberry,
    Cat,
    Butterfly,
    Rainbow,
    Crown,
    Cherry,
    // Mens
    Gamepad,
    Rocket,
    Bolt,
    Flame,
    Coffee,
    Terminal,
    Football,
    Headphones,
    Shield,
    Robot,
    Planet,
    Sunglasses,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Sticker {
    /// Generated by the frontend; only used to tell stickers apart in the UI.
    pub id: String,
    pub kind: StickerKind,
    /// Centre of the sticker, in percent of the window (0–100).
    pub x: f32,
    pub y: f32,
    /// Width in percent of the window's width ([`MIN_SIZE`]–[`MAX_SIZE`]).
    #[serde(default = "default_size")]
    pub size: f32,
    /// Degrees, -180–180.
    #[serde(default)]
    pub rotation: f32,
    /// Mirrored horizontally.
    #[serde(default)]
    pub flip: bool,
}

fn default_size() -> f32 {
    DEFAULT_SIZE
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct Decorations {
    /// Hides every sticker without throwing the arrangement away.
    pub visible: bool,
    /// Paint order: later entries are drawn on top.
    #[serde(deserialize_with = "lenient_stickers")]
    pub stickers: Vec<Sticker>,
}

impl Default for Decorations {
    fn default() -> Self {
        Self {
            visible: true,
            stickers: Vec::new(),
        }
    }
}

impl Decorations {
    /// Clamps every value into range and drops what can't be shown: stickers
    /// past [`MAX_STICKERS`], non-finite numbers, and empty or oversized ids.
    pub fn sanitized(mut self) -> Self {
        self.stickers.retain(|s| {
            !s.id.is_empty()
                && s.id.len() <= 64
                && [s.x, s.y, s.size, s.rotation].iter().all(|v| v.is_finite())
        });
        self.stickers.truncate(MAX_STICKERS);
        for s in &mut self.stickers {
            s.x = s.x.clamp(0.0, 100.0);
            s.y = s.y.clamp(0.0, 100.0);
            s.size = s.size.clamp(MIN_SIZE, MAX_SIZE);
            s.rotation = s.rotation.clamp(-180.0, 180.0);
        }
        self
    }
}

/// Reads the sticker list one entry at a time, skipping any it doesn't
/// understand — art removed in a later version, or a typo made by hand —
/// instead of losing the whole arrangement (or the whole settings file).
fn lenient_stickers<'de, D>(deserializer: D) -> Result<Vec<Sticker>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let value = serde_json::Value::deserialize(deserializer)?;
    let serde_json::Value::Array(items) = value else {
        log::warn!("ignoring sticker list that is not an array");
        return Ok(Vec::new());
    };
    Ok(items
        .into_iter()
        .filter_map(|item| match serde_json::from_value(item) {
            Ok(sticker) => Some(sticker),
            Err(err) => {
                log::warn!("ignoring unrecognized sticker: {err}");
                None
            }
        })
        .collect())
}

/// `Settings::decorations`' reader: a malformed block falls back to the
/// default rather than failing the whole file, and what does parse is
/// sanitized before it reaches managed state.
pub fn lenient_decorations<'de, D>(deserializer: D) -> Result<Decorations, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let value = serde_json::Value::deserialize(deserializer)?;
    let decorations = serde_json::from_value::<Decorations>(value).unwrap_or_else(|err| {
        log::warn!("ignoring unreadable decorations: {err}");
        Decorations::default()
    });
    Ok(decorations.sanitized())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn parse(json: &str) -> Decorations {
        lenient_decorations(&mut serde_json::Deserializer::from_str(json)).unwrap()
    }

    fn sticker(id: &str) -> Sticker {
        Sticker {
            id: id.to_string(),
            kind: StickerKind::Bow,
            x: 50.0,
            y: 50.0,
            size: DEFAULT_SIZE,
            rotation: 0.0,
            flip: false,
        }
    }

    #[test]
    fn reads_the_frontend_shape_and_fills_optional_fields() {
        let d = parse(
            r#"{"visible":false,"stickers":[
                {"id":"a","kind":"bow","x":10,"y":20,"size":9,"rotation":-15,"flip":true},
                {"id":"b","kind":"strawberry","x":90,"y":80},
                {"id":"c","kind":"sunglasses","x":40,"y":40}
            ]}"#,
        );
        assert!(!d.visible);
        assert_eq!(d.stickers.len(), 3);
        assert_eq!(d.stickers[0].kind, StickerKind::Bow);
        assert_eq!(d.stickers[2].kind, StickerKind::Sunglasses);
        assert!(d.stickers[0].flip);
        assert_eq!(d.stickers[1].size, DEFAULT_SIZE);
        assert_eq!(d.stickers[1].rotation, 0.0);
    }

    /// One sticker the app doesn't know must not cost the user the others.
    #[test]
    fn unknown_sticker_is_dropped_and_the_rest_kept() {
        let d = parse(
            r#"{"stickers":[
                {"id":"a","kind":"unicorn","x":10,"y":20},
                {"id":"b","kind":"heart","x":30,"y":40}
            ]}"#,
        );
        assert_eq!(d.stickers.len(), 1);
        assert_eq!(d.stickers[0].kind, StickerKind::Heart);
    }

    #[test]
    fn malformed_block_falls_back_to_default() {
        assert_eq!(parse(r#""lots of bows""#), Decorations::default());
        assert_eq!(parse(r#"{"stickers":"bow"}"#).stickers, Vec::new());
    }

    #[test]
    fn values_are_clamped_and_the_list_capped() {
        let mut wild = sticker("w");
        wild.x = -20.0;
        wild.y = 400.0;
        wild.size = 90.0;
        wild.rotation = 720.0;
        let mut empty_id = sticker("");
        empty_id.x = 1.0;

        let mut stickers = vec![wild, empty_id];
        stickers.extend((0..MAX_STICKERS + 5).map(|i| sticker(&i.to_string())));
        let d = Decorations {
            visible: true,
            stickers,
        }
        .sanitized();

        assert_eq!(d.stickers.len(), MAX_STICKERS);
        assert_eq!(d.stickers[0].x, 0.0);
        assert_eq!(d.stickers[0].y, 100.0);
        assert_eq!(d.stickers[0].size, MAX_SIZE);
        assert_eq!(d.stickers[0].rotation, 180.0);
        assert!(d.stickers.iter().all(|s| !s.id.is_empty()));
    }
}
