//! Files in the Rezure home that tell AI coding agents (Claude Code, Codex,
//! Cursor, ...) what serves this machine's projects. A model knows Laragon
//! from its training data and has never heard of Rezure, so on a machine
//! with both, an agent reading `where php` or a `C:\` listing goes looking
//! for Laragon. These files are how it finds out otherwise:
//!
//! - `AGENTS.md`: what Rezure is, this machine's current state (active PHP,
//!   database, every project with its URL and PHP version) and the rules.
//!   Generated from live state.
//! - `CLAUDE.md`: imports `AGENTS.md`. Claude Code loads `CLAUDE.md` from
//!   every parent folder of where it runs, so a session in a project under
//!   `www\` picks this up with nothing for the user to set up.
//! - `docs\how-rezure-works.md`: the full guide — `agent-docs/` in the repo,
//!   embedded at build time.
//!
//! Only the Rezure home is written to, never a project folder or an agent's
//! own config. A file there that doesn't start with Rezure's marker belongs
//! to someone else and is left alone, the same rule `ca_bundle` follows.

use std::collections::{BTreeSet, HashMap};
use std::path::Path;
use std::time::Duration;

use tauri::{AppHandle, Manager};

use crate::db::projects::{ProjectInfo, ProjectKind};
use crate::db::{self, DbState};
use crate::services::{db_profiles, php, projects};
use crate::utils::paths;

/// The full guide, with `{{home}}` and `{{version}}` filled in on write.
const GUIDE: &str = include_str!("../../agent-docs/how-rezure-works.md");

/// First line of every file written here. Its absence is what marks a file
/// as not Rezure's to overwrite.
const MARKER: &str = "<!-- Generated by Rezure";

/// How often `AGENTS.md` is checked against live state. Nothing is written
/// when it hasn't changed, so this is a comparison, not a rewrite.
const REFRESH_EVERY: Duration = Duration::from_secs(60);

/// This machine's state as `AGENTS.md` reports it — gathered by
/// [`gather`], rendered by [`render_agents_md`] without touching the system.
struct MachineState {
    home: String,
    app_version: String,
    /// Empty when no PHP is installed.
    active_php: String,
    database: Option<DatabaseState>,
    projects: Vec<ProjectState>,
}

struct DatabaseState {
    engine: &'static str,
    version: String,
    port: u16,
    profile: String,
    /// Rezure's own datadir, set up with a passwordless `root`. An adopted
    /// one (Laragon's, XAMPP's) keeps whatever users it already had.
    is_rezures_own: bool,
}

struct ProjectState {
    name: String,
    domain: String,
    path: String,
    linked: bool,
    /// The version that actually serves it — its pin when that's installed,
    /// the active version otherwise.
    php: String,
    pinned: bool,
}

/// Writes all three files, then keeps `AGENTS.md` in step with the machine
/// for as long as the app runs.
pub fn start(app: AppHandle) {
    std::thread::spawn(move || loop {
        refresh(&app);
        std::thread::sleep(REFRESH_EVERY);
    });
}

/// Best-effort: a failure is logged and retried on the next tick. Nothing
/// the user does depends on these files.
fn refresh(app: &AppHandle) {
    let home = match paths::home() {
        Ok(home) => home,
        Err(err) => {
            log::warn!("agent docs: can't resolve the Rezure home: {err}");
            return;
        }
    };
    let state = gather(app, &home);

    write_owned(&home.join("AGENTS.md"), &render_agents_md(&state));
    write_owned(&home.join("CLAUDE.md"), &render_claude_md());
    write_owned(
        &home.join("docs").join("how-rezure-works.md"),
        &render_guide(&state.home, &state.app_version),
    );
}

fn gather(app: &AppHandle, home: &Path) -> MachineState {
    let active_php = php::active_id();
    let installed_php: BTreeSet<String> = php::installed()
        .into_iter()
        .map(|runtime| runtime.version)
        .collect();

    let pins = app
        .try_state::<DbState>()
        .and_then(|db| {
            let conn = db.0.lock().unwrap();
            db::projects::fetch_php_versions(&conn)
                .map_err(|err| log::warn!("agent docs: can't read PHP pins: {err}"))
                .ok()
        })
        .unwrap_or_default();

    let scanned = projects::scan_projects().unwrap_or_else(|err| {
        log::warn!("agent docs: can't list projects: {err}");
        Vec::new()
    });

    MachineState {
        home: home.display().to_string(),
        app_version: app.package_info().version.to_string(),
        projects: project_states(&scanned, &pins, &installed_php, &active_php),
        active_php,
        database: db_profiles::active().map(|profile| DatabaseState {
            engine: profile.engine.label(),
            version: profile.version,
            port: profile.port,
            profile: profile.name,
            is_rezures_own: profile.is_default,
        }),
    }
}

/// Which PHP serves each project, resolved the way `php_pool` does: a pin
/// counts only while that version is installed.
fn project_states(
    scanned: &[ProjectInfo],
    pins: &HashMap<String, Option<String>>,
    installed_php: &BTreeSet<String>,
    active_php: &str,
) -> Vec<ProjectState> {
    scanned
        .iter()
        .filter(|project| !project.missing && !project.domain_invalid)
        .map(|project| {
            let pin = pins
                .get(&project.id)
                .and_then(|pin| pin.as_deref())
                .filter(|version| installed_php.contains(*version));
            ProjectState {
                name: project.name.clone(),
                domain: project.domain.clone(),
                path: project.path.clone(),
                linked: matches!(project.kind, ProjectKind::Linked),
                php: pin.unwrap_or(active_php).to_string(),
                pinned: pin.is_some_and(|version| version != active_php),
            }
        })
        .collect()
}

fn render_agents_md(state: &MachineState) -> String {
    let home = &state.home;
    let mut out = format!(
        "{MARKER} and rewritten while it runs. Edits here are lost. -->\n\
         # Rezure: this machine's local dev server\n\
         \n\
         The local web stack on this machine (Nginx, PHP, MariaDB/MySQL, Mailpit) is \
         managed by **Rezure**, a Windows app like Laragon or XAMPP. Projects in \
         `{home}\\www\\` and the ones listed below are served by Rezure, **not by \
         Laragon or XAMPP**, even if `C:\\laragon` or `C:\\xampp` exists.\n\
         \n\
         How it all works, and what not to touch: `{home}\\docs\\how-rezure-works.md`. \
         Read it before changing web server, PHP, hosts or database settings.\n\
         \n\
         ## Current state\n\
         \n"
    );

    if state.active_php.is_empty() {
        out.push_str("- **PHP:** none installed yet.\n");
    } else {
        out.push_str(&format!(
            "- **PHP:** {} is active (`{home}\\current\\php`). Projects can pin their own version.\n",
            state.active_php
        ));
    }
    match &state.database {
        Some(db) => {
            let login = if db.is_rezures_own {
                "user `root`, empty password"
            } else {
                "an adopted data folder, so its own users and passwords apply (Laragon and XAMPP \
                 default to `root` with an empty password)"
            };
            out.push_str(&format!(
                "- **Database:** {} {} on `127.0.0.1:{}`, {login} (profile \"{}\").\n",
                db.engine, db.version, db.port, db.profile
            ));
        }
        None => out.push_str("- **Database:** no profile set up yet.\n"),
    }
    out.push_str(
        "- **Web:** Nginx on port 80, plain HTTP. Each project is `http://<name>.test`.\n\
         - **Mail:** Mailpit, SMTP `127.0.0.1:1025`, inbox `http://127.0.0.1:8025`.\n\
         - Services may be stopped. Rezure starts them only when the user asks. Check with \
         `Get-Process nginx, php-cgi, mysqld, mailpit -ErrorAction SilentlyContinue`.\n",
    );

    out.push_str("\n## Projects\n\n");
    if state.projects.is_empty() {
        out.push_str(&format!(
            "None yet. A project is a folder in `{home}\\www\\`.\n"
        ));
    } else {
        out.push_str("| Project | URL | Folder | PHP |\n|---|---|---|---|\n");
        for project in &state.projects {
            let folder = if project.linked {
                format!("`{}` (linked)", project.path)
            } else {
                format!("`{}`", project.path)
            };
            let php = match (project.php.is_empty(), project.pinned) {
                (true, _) => "-".to_string(),
                (false, true) => format!("{} (pinned)", project.php),
                (false, false) => project.php.clone(),
            };
            out.push_str(&format!(
                "| {} | http://{} | {folder} | {php} |\n",
                escape_cell(&project.name),
                project.domain,
            ));
        }
    }

    out.push_str(&format!(
        "\n## Rules\n\n\
         - Start, stop and restart services, switch PHP versions and sync the hosts file \
         **from the Rezure app**. Don't launch or kill `nginx.exe`, `php-cgi.exe`, \
         `mysqld.exe` or `mailpit.exe` yourself.\n\
         - PHP settings go in `{home}\\etc\\php\\conf.d\\*.ini`. Everything under \
         `{home}\\data\\` is regenerated, so edits there don't last.\n\
         - Run `php artisan`, `composer` and `npm` from the terminal a project card opens, \
         which has that project's PHP and Node first on `PATH`. Elsewhere, check \
         `where php` first.\n"
    ));
    out
}

/// A project name is a folder name, which can hold a `|`.
fn escape_cell(text: &str) -> String {
    text.replace('|', "\\|")
}

fn render_claude_md() -> String {
    format!(
        "{MARKER}. Edits here are lost. -->\n\
         <!-- Claude Code loads this from every parent folder, so sessions in Rezure projects get it. -->\n\
         @AGENTS.md\n"
    )
}

fn render_guide(home: &str, app_version: &str) -> String {
    let body = GUIDE
        .replace("{{home}}", home)
        .replace("{{version}}", app_version);
    format!("{MARKER} from the copy bundled with the app. Edits here are lost. -->\n{body}")
}

/// Writes `content` to `path` unless the file is someone else's (no marker)
/// or already says exactly this.
fn write_owned(path: &Path, content: &str) {
    match std::fs::read_to_string(path) {
        Ok(existing) if existing == content => return,
        Ok(existing) if !existing.starts_with(MARKER) => {
            log::info!(
                "agent docs: leaving {} alone, Rezure didn't write it",
                path.display()
            );
            return;
        }
        _ => {}
    }
    if let Some(parent) = path.parent() {
        if let Err(err) = std::fs::create_dir_all(parent) {
            log::warn!("agent docs: can't create {}: {err}", parent.display());
            return;
        }
    }
    if let Err(err) = std::fs::write(path, content) {
        log::warn!("agent docs: can't write {}: {err}", path.display());
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn project(id: &str, kind: ProjectKind) -> ProjectInfo {
        ProjectInfo {
            id: id.to_string(),
            name: id.to_string(),
            path: format!(r"C:\rezure\www\{id}"),
            domain: format!("{id}.test"),
            stack: "Laravel".to_string(),
            has_hosts_entry: true,
            last_opened_at: None,
            open_count: 0,
            kind,
            missing: false,
            domain_invalid: false,
            php_version: None,
            node_version: None,
        }
    }

    fn state(projects: Vec<ProjectState>) -> MachineState {
        MachineState {
            home: r"C:\rezure".to_string(),
            app_version: "3.0.0".to_string(),
            active_php: "8.3.33".to_string(),
            database: Some(DatabaseState {
                engine: "MariaDB",
                version: "11.2.2".to_string(),
                port: 3306,
                profile: "Rezure".to_string(),
                is_rezures_own: true,
            }),
            projects,
        }
    }

    #[test]
    fn a_pin_counts_only_while_that_version_is_installed() {
        let scanned = vec![
            project("blog", ProjectKind::Scanned),
            project("legacy", ProjectKind::Scanned),
            project("gone", ProjectKind::Linked),
        ];
        let pins = HashMap::from([
            ("legacy".to_string(), Some("7.4.33".to_string())),
            ("gone".to_string(), Some("5.6.40".to_string())),
        ]);
        let installed = BTreeSet::from(["8.3.33".to_string(), "7.4.33".to_string()]);

        let states = project_states(&scanned, &pins, &installed, "8.3.33");

        assert_eq!(
            (states[0].php.as_str(), states[0].pinned),
            ("8.3.33", false)
        );
        assert_eq!((states[1].php.as_str(), states[1].pinned), ("7.4.33", true));
        assert_eq!(
            (states[2].php.as_str(), states[2].pinned),
            ("8.3.33", false)
        );
        assert!(states[2].linked);
    }

    #[test]
    fn projects_that_are_not_served_are_left_out() {
        let mut missing = project("moved", ProjectKind::Linked);
        missing.missing = true;
        let mut invalid = project("bad", ProjectKind::Scanned);
        invalid.domain_invalid = true;

        let states = project_states(
            &[missing, invalid],
            &HashMap::new(),
            &BTreeSet::new(),
            "8.3.33",
        );

        assert!(states.is_empty());
    }

    #[test]
    fn agents_md_names_rezure_and_lists_each_project() {
        let md = render_agents_md(&state(vec![ProjectState {
            name: "shop".to_string(),
            domain: "shop.test".to_string(),
            path: r"D:\code\shop".to_string(),
            linked: true,
            php: "7.4.33".to_string(),
            pinned: true,
        }]));

        assert!(md.starts_with(MARKER));
        assert!(md.contains("not by Laragon or XAMPP"));
        assert!(md.contains(r"C:\rezure\docs\how-rezure-works.md"));
        assert!(md.contains("MariaDB 11.2.2 on `127.0.0.1:3306`"));
        assert!(
            md.contains(r"| shop | http://shop.test | `D:\code\shop` (linked) | 7.4.33 (pinned) |")
        );
    }

    #[test]
    fn an_adopted_datadir_is_not_promised_an_empty_root_password() {
        let mut adopted = state(Vec::new());
        adopted.database = Some(DatabaseState {
            engine: "MySQL",
            version: "8.4.3".to_string(),
            port: 3306,
            profile: "Laragon 8.4.3".to_string(),
            is_rezures_own: false,
        });

        let md = render_agents_md(&adopted);

        assert!(md.contains("its own users and passwords apply"));
        assert!(!md.contains("user `root`, empty password"));
    }

    #[test]
    fn a_pipe_in_a_project_name_does_not_break_the_table() {
        assert_eq!(escape_cell("a|b"), r"a\|b");
    }

    #[test]
    fn the_guide_is_filled_in_for_this_machine() {
        let guide = render_guide(r"D:\dev\rezure", "3.0.0");

        assert!(guide.starts_with(MARKER));
        assert!(guide.contains(r"D:\dev\rezure\etc\php\conf.d"));
        assert!(guide.contains("Rezure 3.0.0"));
        assert!(!guide.contains("{{"));
    }

    #[test]
    fn claude_md_imports_agents_md() {
        let md = render_claude_md();
        assert!(md.starts_with(MARKER));
        assert!(md.lines().any(|line| line == "@AGENTS.md"));
    }

    #[test]
    fn a_file_rezure_did_not_write_is_left_alone() {
        let dir = std::env::temp_dir().join(format!("rezure-agent-docs-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let theirs = dir.join("AGENTS.md");
        std::fs::write(&theirs, "my own notes").unwrap();
        let ours = dir.join("CLAUDE.md");

        write_owned(&theirs, &render_claude_md());
        write_owned(&ours, &render_claude_md());

        assert_eq!(std::fs::read_to_string(&theirs).unwrap(), "my own notes");
        assert_eq!(std::fs::read_to_string(&ours).unwrap(), render_claude_md());
        std::fs::remove_dir_all(&dir).unwrap();
    }
}
